const PREFIX = 'todos';

export const COMPLETE = `${PREFIX}/COMPLETE`
export const SUBMIT = `${PREFIX}/SUBMIT`
export const ADDDESCRIPTION = `${PREFIX}/ADDESCRIPTION`
export const DELETETODO = `${PREFIX}/DELETETODO`
export const DELETEALLTASKS = `${PREFIX}/DELETEALLTASKS`